<?php

namespace App\Modules\Samples\Models;

use App\Modules\Samples\Enums\ManifestStatus;
use App\Modules\Shared\Models\BaseModel;
use App\Modules\Shared\Scoping\BelongsToScope;
use App\Modules\Shared\Scoping\HasScopeColumns;
use App\Modules\Shared\Scoping\ScopeColumns;
use Carbon\CarbonImmutable;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * A transport bag of samples from one branch to one lab (table
 * `sample_transfers`, spec §7.6). Seen by both ends of the route.
 *
 * @property string $id
 * @property string $organization_id
 * @property string $manifest_no
 * @property string $from_branch_id
 * @property string $to_branch_id
 * @property string|null $dispatched_by
 * @property CarbonImmutable|null $dispatched_at
 * @property string|null $courier_name
 * @property bool|null $temperature_ok
 * @property string|null $dispatch_temp_c
 * @property string|null $receipt_temp_c
 * @property string|null $received_by
 * @property CarbonImmutable|null $received_at
 * @property ManifestStatus $status
 * @property CarbonImmutable|null $missing_flagged_at
 * @property Collection<int, ManifestItem> $items
 */
final class Manifest extends BaseModel implements HasScopeColumns
{
    use BelongsToScope;

    protected $table = 'sample_transfers';

    /** The open-bag flag is generated by the database. */
    protected $hidden = ['is_open'];

    protected function casts(): array
    {
        return [
            'dispatched_at' => 'immutable_datetime',
            'temperature_ok' => 'boolean',
            'received_at' => 'immutable_datetime',
            'status' => ManifestStatus::class,
            'missing_flagged_at' => 'immutable_datetime',
        ];
    }

    public static function scopeColumns(): ScopeColumns
    {
        return new ScopeColumns(branch: 'from_branch_id', otherBranches: ['to_branch_id']);
    }

    /** @return HasMany<ManifestItem, $this> */
    public function items(): HasMany
    {
        return $this->hasMany(ManifestItem::class, 'transfer_id');
    }
}
